### ISSUE TITLE
Facebook OAuth Token as HTML instead of JSON fails

### ISSUE THREAD

**Issue by BirknerAlex** [google/signet#86]
Hello,

I've started to use this Library for our Website project. I've already implemented Google Sign-In to our website which works fine. Now I am trying to integrate the Facebook Login too. 

But it seems like Facebook don't respond with JSON after creating the Token. That's mostly what my code looks like:

```ruby
client = Signet::OAuth2::Client.new(
   :authorization_uri => "https://www.facebook.com/#{self::FACEBOOK_GRAPH_VERSION}/dialog/oauth",
   :token_credential_uri =>  "https://graph.facebook.com/#{self::FACEBOOK_GRAPH_VERSION}/oauth/access_token",
   :client_id => 'XXXXXX',
   :client_secret => 'XXXXXX',
   :scope => 'public_profile email',
   :redirect_uri => "#{API_URL}/oauth/v2/third_party/facebook",
   :state => state
)

client.code = params['code']
client.fetch_access_token! # here will be the error thrown
```

```
#<ArgumentError: Invalid content type 'text/plain; charset=UTF-8'>
["/usr/local/rvm/gems/ruby-2.3.3/gems/signet-0.7.3/lib/signet/oauth_2.rb:86:in `parse_credentials'",
 "/usr/local/rvm/gems/ruby-2.3.3/gems/signet-0.7.3/lib/signet/oauth_2/client.rb:975:in `fetch_access_token'",
 "/usr/local/rvm/gems/ruby-2.3.3/gems/signet-0.7.3/lib/signet/oauth_2/client.rb:998:in `fetch_access_token!'",
 "..............third_party_controller.rb:62:in `facebook'",
```

Is there any chance to set the Content-Type or Accept Header for this request? I think that should be the issues, don't know why Facebook responds by default with HTML.

Regards,
Alex

**Comment by BirknerAlex** [comment]
Hello,

using a newer Graph Version fixed it.
